language: scala
sudo: required
env:
  global:
  - TRAVIS_NODE_VERSION="8"
  - secure: YXQWJjmqrib8ePEp/Ds7US9P5+medDAsKc8X/zHcwoNIGIpJF6QyBqkvLJNq5IkM05K0AF8AGmz2BlS1XECIYkTdQVS0dITrEFuiaiiUzURNlhJGjtw10NAS99+dW3M/T4MKWvTgWcIsgEx0ttsTlMedWpm7aFS4Zn9i3sx2iUSHmck74JTHUcI/1DltgwTu73euxgNBPSl6ICDKEcwRgjCor55/HLbhiHBS6nx/OVPiazFrsnOG8psfn8NZUJMYiNK4FL69BxHHyvs1mQx0U24Yxbg/r2U+QrPihq5Xk9MglDz13wjxu0WrVQdFZzLRxmnTXpRr/Kx9l4xN4IMvg0hNeJ0tBCq2g3i1XXeIkf0LM0ZoImV7pB4JWUYywUyGwz5/NLiJH82dVpXO3YtHl5kF22+Vtd+IOSWmVkx4bW+UTW3vLXDyxfULscNLGb3yeuTcW10NLAlXSakNvukyYoA3K7BGoN4J3v36CzKcO3wD1hzSChhd3ivngtuKF+rdKiJTjzVd/hnwTF7xZ7CNpGSDoggT/NQ4oHIWTdWBcMDI61H76eMOittphBOOfYEcXYPwBrDSMHDnPKyoNdWc3VItCAYp5dqZxtNxkclIEzGHjOEB03II5zDhF+uv4YPxaf2IYhhcLsdE5JHltpa9CVnTciJdrJ6nKx4vNBqzRhM=
  - secure: CGqZrHZPgWOVZcjCL4iDJRlYPeC46Ko53ZufP4UtKpC7bdXgzqsbLVinI0EYwjZ0MZNUFQhOSKCK+2tNcnVA0EkhzMLSBE2sHXQ3fwO3EsoSGLCEOKh2LSrxb2S2AXHJer2/EsoJMCVyaYaQdWKWuK+CGLeTDJtP4l5Zeo1pF9kZOKDnaHHVmutnrbzcl39vsLOxFebaY5RP41irPKFV43bfUqfs5eoUslwt17QFLrXHQP7wlG9wzDwtqC2oonHO0GDWFs5NM2tju/J4FC31wFFslIEQ8Pabt8D4qGj+3rXt4KNiMM3v7G0kC1IYBEChVSrBcPMOljDWvMYYbqcAeIfLu/RsWGUX+e/e3FD6bbhoNIAAelYWqukPkvIFy4Y0iYjxFV6YZngiyuAgh+3+vwvhyQKh71hgVRxoVWFp3SXawj3mSnsDI6m4Dj9lO0lNG+eAEmFQfrmN2GC7OKhyT0/clazaYsdcKW2XsQN1qglWevepRtiOWO2vP6zBT8HHN8DV7YPLsZel3RMoqtkks5GWA0khu2yaWsCTz9i7RdPoFjdJdDJSgQG1Ta/1Dc6JuvgMOEJ3CQsZAMGZV9URu7m0m8iuLLOW5vglYQuIw5kjTgCF3r50QV5QgamLlrOkOUGd2DRv7jjFFBNpK9k0ndNCt7NEcKgbD8O8ne0UAp4=
  - secure: GRw7LuKilmu8IwGQo4G9UQUyG1IbVVewqlmEGxzdBj0hFwuPIc/hEfSS0g3CTA87iA+d960wsxwBpssu/e5sHk9RV5378W9MavGaTva8ifGNiMLn+lCEtA9sMr+eB+fTpdGh+PGqR9EDeeI6lMuuKGEUUDaxWAR198dP30DnfoZ4AHAV6QSyMHd2yPQa3lP+MPgZ8RnUok5ucEXSpkcwDpeptnl7WVirh6rIw9S6bJdN8eDKbapz+fXev3QECI8cJtU92AQAMnoQ9nkD4eI48yLg+EqXhTdZwls5lHLa1RW4XGhtt+26zOi/4/Mw/FoV5Nx6KszHO1nUq2AXCfXHINmZar9KmZt9ZCPL6Ap0/LXz6USrnz/EARHt08VMWXk4TXZu90ZYFglW/Tle1KEX6pV4hKvdrnDvqKlQvMBgm6fJvCIzbUtzeks5mhV1TWhm/l4UG0mBi4EqAjZsoM8QZ+cXMeiA+JQxLyE/a6Mf3ejWeqYsBfaOveRNiJID5tc+H2a1jwaDJq1lh78WYWqR8uq9husZas+VNVMwFAyt3w3ew/d3Z0kcmzOaujZC3OFmI20qd3+Aep9o32Qn1rCmRXmfD5IQFDx1OoR6bjfwDNoa2YDE/a9fH8MfFWqDam6C5PDOL0EPTe/PJUUY4Kk+6/x2Tm5bhQEXXt0RxZ23FBI=
  matrix:
  - TRAVIS_SBT_VERSION="0.13.17"  SCALAJS_VERSION="0.6.31"
  - TRAVIS_SBT_VERSION="1.2.8"    SCALAJS_VERSION="1.0.0-RC2"
  - TRAVIS_SBT_VERSION="1.2.8"    SCALAJS_VERSION="0.6.31"
jdk:
  - openjdk11
before_install:
- nvm install 6
- nvm use 6
- node --version
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
- export PATH=$HOME/.yarn/bin:$PATH
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
    openssl aes-256-cbc -K $encrypted_d49db7ad02d6_key -iv $encrypted_d49db7ad02d6_iv -in travis/secrets.tar.enc -out travis/secrets.tar -d;
    tar xv -C travis -f travis/secrets.tar;
  fi
script:
- sbt -no-colors ";^^$TRAVIS_SBT_VERSION;test;runScripted"
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ -n "$TRAVIS_TAG" ]; then
   sbt ";^^$TRAVIS_SBT_VERSION; publishSigned; sonatypeReleaseAll; manual/makeSite; manual/ghpagesPushSite";
  fi
cache:
  yarn: true
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
