version: '{build}'
os: Windows Server 2012
environment:
  matrix:
    - CI_SBT_VERSION: 1.2.8
      SCALAJS_VERSION: 1.0.0
install:
  - ps: Install-Product node 12
  - cmd: choco install sbt --version 1.4.0 -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
build: off
test_script:
  - cmd: sbt ";^^%CI_SBT_VERSION%;test;runScripted"
cache:
  - C:\sbt
  - C:\Users\appveyor\.ivy2\cache
  - C:\Users\appveyor\.sbt
